import random
import creds
import textwrap
from csh.webnews import Webnews


def select():
    with open('names.txt', 'r+') as namesfile:
        names = namesfile.readlines() 
        assignees = random.sample(names, min(3, len(names)))
        [names.remove(n) for n in assignees]
        namesfile.seek(0)
        namesfile.write(''.join(names))
        namesfile.truncate()
        return [a.strip() for a in assignees]


def name_list(names):
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return " and ".join(names)
    initial = ', '.join(names[:-1])
    return initial + " and " + names[-1]


def message(assignees):
    '''
    Takes a tuple of names
    Returns a formatted a template
    '''
    msg_title = 'Room Cleaners for the Week'
    msg_body = textwrap.dedent(
               '''
               This weeks cleaners are {}.
               As always, they will be responsible for cleaning the Lounge,
               User Center, and Software room. It is up to you three to decide how
               to divy the work.

               Here are some basic things that should be completed each time a room is cleaned:
               - Surfaces are wiped down with disinfectant wipes or cleanser, don't forget the doors
               - Windows and glass is cleaned.
               - Pick up any garbage (look around)
               - Vacuum each room, the floor vacuum is in the RA's room.

               If you have any questions, talk to Imps.

               This post generated by the cleaning bot.
               '''.format(name_list(assignees)))
    return msg_title, msg_body


if __name__ == '__main__':
    names = select()
    if not names:
        print("Nobody left to clean. Re-fill the name list and try again.")
        exit(1)
    title, body = message(names)
    newsgroup = 'csh.committee.house-imps'
    print body
    wn = Webnews(creds.api_key, creds.api_agent)
    wn.compose(newsgroup=newsgroup,
               subject=title,
               body=body)
